name: Budget Guard (stub)
on:
  schedule:
    - cron: "0 13 * * *"  # daily 13:00 UTC
  workflow_dispatch:
permissions:
  contents: read
  issues: write
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Budget summary (stub)
        run: |
          echo "Token budget: $25/day; Cloud budget: $10/day"
          echo "Integrate Actions billing + token metering later."
      - name: Open/Update Budget Note
        uses: actions/github-script@v7
        with:
          script: |
            const today = new Date().toISOString().slice(0,10)
            const title = `Budget Note ${today}`
            const issues = await github.paginate(github.rest.issues.listForRepo, {owner: context.repo.owner, repo: context.repo.repo, state: 'open'})
            const existing = issues.find(i => i.title === title)
            const body = "Budget guard stub ran. Hook to billing & token meters next."
            if (existing) {
              await github.rest.issues.update({owner: context.repo.owner, repo: context.repo.repo, issue_number: existing.number, body})
            } else {
              await github.rest.issues.create({owner: context.repo.owner, repo: context.repo.repo, title, body})
            }
